#!/usr/bin/env python3
"""Generate the README skill catalog from each skill's SKILL.md frontmatter.

The frontmatter is the only thing Claude actually reads, so it is the only
source of truth. Every other copy of a skill's description drifted: before this
script existed, 68% of the entries in the old hand-maintained skills.json no
longer matched their frontmatter, and one advertised a Linear-writing skill as
having no side effects.

    python3 scripts/build_catalog.py          # rewrite the README table
    python3 scripts/build_catalog.py --check  # fail if it would change (CI)
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
START = "<!-- BEGIN GENERATED CATALOG -->"
END = "<!-- END GENERATED CATALOG -->"


def frontmatter(path: Path) -> dict:
    """Parse just enough YAML for our fields. Avoids a PyYAML dependency so the
    check runs anywhere, and tolerates the block scalars (`>-`) used throughout."""
    text = path.read_text()
    if not text.startswith("---\n"):
        return {}
    body = text.split("---\n", 2)[1]
    out, key, buf = {}, None, []

    def flush():
        if key:
            out[key] = " ".join(w.strip() for w in buf).strip()

    for line in body.split("\n"):
        m = re.match(r"^([a-zA-Z][\w-]*):\s*(.*)$", line)
        if m:
            flush()
            key, rest = m.group(1), m.group(2).strip()
            buf = [] if rest in (">-", "|", ">", "|-", "") else [rest]
        elif key and (line.startswith("  ") or line.startswith("\t")):
            buf.append(line)
        elif line.strip() == "":
            continue
        else:
            flush()
            key, buf = None, []
    flush()
    return {k: v.strip().strip('"').strip("'") for k, v in out.items()}


def skills():
    for platform in ("code", "desktop"):
        for skill_md in sorted((ROOT / platform).glob("*/SKILL.md")):
            d = skill_md.parent
            fm = frontmatter(skill_md)
            desc = re.sub(r"\s+", " ", fm.get("description", "")).strip()
            # The catalog is an index, not a spec — one sentence is the right size.
            first = re.split(r"(?<=[.!?])\s+", desc)[0] if desc else "_(no description)_"
            yield {
                "name": d.name,
                "platform": platform,
                "path": f"{platform}/{d.name}/SKILL.md",
                "summary": first,
                "icon": (d / "icon.svg").exists(),
                # Derived, never hand-set: the frontmatter already states it.
                "side_effects": fm.get("disable-model-invocation", "").lower()
                in ("true", "yes", "on", "1"),
            }


def table(rows):
    out = ["| Skill | What it does | Side effects |", "|---|---|---|"]
    for s in rows:
        icon = (
            f'<img src="{s["platform"]}/{s["name"]}/icon.svg" width="20" height="20" '
            f'alt="" valign="middle"> &nbsp; '
            if s["icon"] else ""
        )
        out.append(
            f'| {icon}[`/{s["name"]}`]({s["path"]}) | {s["summary"]} | '
            f'{"Yes" if s["side_effects"] else "No"} |'
        )
    return "\n".join(out)


def render():
    rows = list(skills())
    code = [s for s in rows if s["platform"] == "code"]
    desktop = [s for s in rows if s["platform"] == "desktop"]
    parts = [
        START,
        "<!-- Generated by scripts/build_catalog.py from each SKILL.md frontmatter.",
        "     Do not edit by hand: run `make catalog`. -->",
        "",
        f"### Claude Code ({len(code)})",
        "",
        table(code),
        "",
        f"### Claude Desktop ({len(desktop)})",
        "",
        table(desktop),
        "",
        END,
    ]
    return "\n".join(parts)


def main():
    check = "--check" in sys.argv
    readme = ROOT / "README.md"
    text = readme.read_text()
    if START not in text or END not in text:
        sys.exit(f"README.md is missing the {START} / {END} markers.")
    new = text[: text.index(START)] + render() + text[text.index(END) + len(END):]
    if check:
        if new != text:
            sys.exit("README catalog is out of date — run `make catalog`.")
        print(f"catalog up to date ({len(list(skills()))} skills)")
        return
    readme.write_text(new)
    print(f"catalog written ({len(list(skills()))} skills)")


if __name__ == "__main__":
    main()
